/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Customer.AssignCusToFlightList;
import Business.Customer.CustomeProfileList;
import Business.Customer.CustomerDirectory;
import Business.Flight.FlightSchedule;
import UserInterface.ManagerAirliners.AirlinerLoginJPanel;
import UserInterface.ManagerAirliners.CreateAirlinerJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class AirlinerIssueWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel cardSequence;
    private CustomerDirectory customerDirectory;
    private CustomeProfileList cusPros;
    private FlightSchedule flightSchedule;
    private AssignCusToFlightList assignList;
    public AirlinerIssueWorkAreaJPanel(JPanel cardSequence) {
        initComponents();
        this.cardSequence=cardSequence;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddAirliner = new javax.swing.JButton();
        btnLogInAirliner = new javax.swing.JButton();
        btnManageAirliner = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddAirliner.setText("Create Airliner");
        btnAddAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirlinerActionPerformed(evt);
            }
        });
        add(btnAddAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 170, 30));

        btnLogInAirliner.setText("Log in Airliner");
        btnLogInAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInAirlinerActionPerformed(evt);
            }
        });
        add(btnLogInAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, -1));

        btnManageAirliner.setText("Manager Airliners");
        btnManageAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirlinerActionPerformed(evt);
            }
        });
        add(btnManageAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirlinerActionPerformed
        CreateAirlinerJPanel createAirlinerJPanel = new CreateAirlinerJPanel(cardSequence);
        cardSequence.add("CreateAirlinerJPanel", createAirlinerJPanel);
        CardLayout layout = (CardLayout) cardSequence.getLayout();
        layout.next(cardSequence);
    }//GEN-LAST:event_btnAddAirlinerActionPerformed

    private void btnLogInAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInAirlinerActionPerformed
        //        CreateAirlinerJPanel createAirlinerJPanel = new CreateAirlinerJPanel(this.cardSequenceJPanel);
        //        this.cardSequenceJPanel.add("CreateAirlinerJPanel", createAirlinerJPanel);
        //        CardLayout layout = (CardLayout) this.cardSequenceJPanel.getLayout();
        //        layout.next(this.cardSequenceJPanel);
        AirlinerLoginJPanel airlinerLoginJPanel = new AirlinerLoginJPanel(cardSequence);
        cardSequence.add("AirlinerLoginJPanel", airlinerLoginJPanel);
        CardLayout layout = (CardLayout) cardSequence.getLayout();
        layout.next(cardSequence);
    }//GEN-LAST:event_btnLogInAirlinerActionPerformed

    private void btnManageAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirlinerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageAirlinerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirliner;
    private javax.swing.JButton btnLogInAirliner;
    private javax.swing.JButton btnManageAirliner;
    // End of variables declaration//GEN-END:variables
}
