/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

/**
 *
 * @author admin
 */
public class BookFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookFlightsJPanel
     */
    public BookFlightJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDepartAirport = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtArrivalTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtArrivalAirport = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumOfSeats = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDepartTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboRow = new javax.swing.JComboBox<>();
        comboColumn = new javax.swing.JComboBox<>();
        BtnSubmit = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Departion Airport:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        txtDepartAirport.setEnabled(false);
        add(txtDepartAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 220, 30));

        jLabel2.setText("Arrival Time:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        txtArrivalTime.setEnabled(false);
        add(txtArrivalTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 220, 30));

        jLabel3.setText("Arriavl Airport:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        txtArrivalAirport.setEnabled(false);
        add(txtArrivalAirport, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 220, 30));

        jLabel4.setText("Remain Seats:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        txtNumOfSeats.setEnabled(false);
        add(txtNumOfSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 220, 30));

        jLabel6.setText("Airliner Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        txtAirlinerName.setEnabled(false);
        add(txtAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 220, 30));

        jLabel7.setText("Departion Time:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        txtDepartTime.setEnabled(false);
        add(txtDepartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Book A Flight");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 240, 40));

        BtnBack.setText("<< Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel8.setText("Name:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 220, 30));

        jLabel9.setText("ID:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 220, 30));

        jLabel10.setText("Phone:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 220, 30));

        jLabel11.setText("Select Seat:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        comboRow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));
        add(comboRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        comboColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Window", "Middle", "Aisle" }));
        add(comboColumn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, -1, -1));

        BtnSubmit.setText("Submit");
        add(BtnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JComboBox<String> comboColumn;
    private javax.swing.JComboBox<String> comboRow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtArrivalAirport;
    private javax.swing.JTextField txtArrivalTime;
    private javax.swing.JTextField txtDepartAirport;
    private javax.swing.JTextField txtDepartTime;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumOfSeats;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
