/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Customer.AssignCusToFlight;
import Business.Customer.AssignCusToFlightList;
import Util.DateUtil;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class CusProWithTicketsJPanel extends javax.swing.JPanel {

    private JPanel cardSequence;
    private AssignCusToFlightList actfList;
    public CusProWithTicketsJPanel(JPanel cardSequence,AssignCusToFlightList actfList) {
        initComponents();
        this.cardSequence=cardSequence;
        this.actfList=actfList;
        populate();
    }
    
    public void populate(){
        DefaultTableModel dtm=(DefaultTableModel)tblList.getModel();
        dtm.setRowCount(0);
        for(AssignCusToFlight i:actfList.getActfList()){
            Object[] row=new Object[7];
            row[0]=i.getCusPro().getCustomer().getName();
            row[1]=i.getCusPro().getCustomer().getPhone();
            row[2]=i.getFlight().getFlightNumber();
            row[3]=DateUtil.totYyyyMmDd(i.getFlight().getTakeOffTime());
            row[4]=i.getFlight().getTakeOffPlace().toString();
            row[5]=i.getFlight().getLandingPlace().toString();
            row[6]=i.getTicket().getSeat().getRow()+""+i.getTicket().getSeat().getSeatNo(); 
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "FlightCode", "DepartTime", "From", "To", "Seat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblList);
        if (tblList.getColumnModel().getColumnCount() > 0) {
            tblList.getColumnModel().getColumn(0).setResizable(false);
            tblList.getColumnModel().getColumn(1).setResizable(false);
            tblList.getColumnModel().getColumn(2).setResizable(false);
            tblList.getColumnModel().getColumn(3).setResizable(false);
            tblList.getColumnModel().getColumn(4).setResizable(false);
            tblList.getColumnModel().getColumn(5).setResizable(false);
            tblList.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 660, 160));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        cardSequence.remove(this);
        CardLayout layout=(CardLayout)cardSequence.getLayout();
        layout.previous(cardSequence);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    // End of variables declaration//GEN-END:variables
}
