/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManagerAirliners;

import Business.Airliners.Airliner;
import Business.Airliners.AirlinerDirectory;
import Business.Airliners.AirlinerProfile;
import Business.Airliners.AirlinerProfileList;
import Business.Airplane.Airplane;
import Business.Flight.Flight;
import Business.Flight.FlightSchedule;
import UserInterface.TravelAgencyMain;
import Util.Address;
import com.eltima.components.ui.DatePicker;

import javax.swing.*;
import java.awt.*;
import java.util.Date;

/**
 *
 * @author wangcong
 */
public class AddAirplaneJPanel extends javax.swing.JPanel {

    private final JPanel cardSequenceJPanel;

    private final Airliner airliner;

    /**
     * Creates new form AddAirplaneJPanel
     */
    public AddAirplaneJPanel(JPanel cardSequenceJPanel, Airliner airliner) {
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.airliner = airliner;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        lblAirplaneId = new javax.swing.JLabel();
        txtAirPlaneId = new javax.swing.JTextField();
        lblAirplaneModel = new javax.swing.JLabel();
        lblAirplaneAge = new javax.swing.JLabel();
        txtAirPlaneAge = new javax.swing.JTextField();
        lblAirplaneSeats = new javax.swing.JLabel();
        txtAirPlaneSeats = new javax.swing.JTextField();
        comboBoxAirplaneModel = new javax.swing.JComboBox<>();
        btnAddPlane = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        datePickerTakeOff = new com.eltima.components.ui.DatePicker();
        txtFlightNumber = new javax.swing.JTextField();
        txtTakeOffCountry = new javax.swing.JTextField();
        takeOffHour = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        takeOffMin = new javax.swing.JTextField();
        lblLandingTime = new javax.swing.JLabel();
        datePickerLanding = new com.eltima.components.ui.DatePicker();
        landingHour = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        landingMin = new javax.swing.JTextField();
        txtTakeOffCity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAirliner = new javax.swing.JTextField();
        txtLandingCountry = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLandingCity = new javax.swing.JTextField();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Add Your Flight");

        lblAirplaneId.setText("Airplane ID:");

        lblAirplaneModel.setText("Airplane Model:");

        lblAirplaneAge.setText("Airplane Age:");

        lblAirplaneSeats.setText("Airplane Seats:");

        comboBoxAirplaneModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));

        btnAddPlane.setText("Add Plane");
        btnAddPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlaneActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");

        jLabel2.setText("Take Off Country:");

        jLabel3.setText("Take Off City:");

        jLabel4.setText("Flight Number:");

        jLabel5.setText("Take off time:");

        txtFlightNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlightNumberActionPerformed(evt);
            }
        });

        takeOffHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeOffHourActionPerformed(evt);
            }
        });

        jLabel6.setText(":");

        lblLandingTime.setText("Landing Time:");

        landingHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landingHourActionPerformed(evt);
            }
        });

        jLabel26.setText(":");

        jLabel7.setText("Airliner:");

        txtAirliner.setText(airliner.getName());
        txtAirliner.setEditable(false);

        jLabel8.setText("Landing City:");

        jLabel9.setText("Landing Country:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAirplaneSeats)
                            .addComponent(lblAirplaneAge)
                            .addComponent(lblAirplaneModel)
                            .addComponent(lblAirplaneId)
                            .addComponent(jLabel5)
                            .addComponent(lblLandingTime))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAirPlaneSeats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtAirPlaneId)
                                    .addComponent(comboBoxAirplaneModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAirPlaneAge))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFlightNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(txtTakeOffCity, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTakeOffCountry, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(datePickerLanding, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(landingHour, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(datePickerTakeOff, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(takeOffHour, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(landingMin, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                    .addComponent(takeOffMin))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAirliner)
                                    .addComponent(txtLandingCity)
                                    .addComponent(txtLandingCountry))))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnBack)
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1)))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddPlane)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirplaneId)
                    .addComponent(txtAirPlaneId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirplaneModel)
                    .addComponent(comboBoxAirplaneModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTakeOffCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirplaneAge)
                    .addComponent(txtAirPlaneAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTakeOffCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtLandingCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtLandingCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAirplaneSeats)
                            .addComponent(txtAirPlaneSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(datePickerTakeOff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(takeOffHour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(takeOffMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblLandingTime)))
                        .addGap(89, 89, 89)
                        .addComponent(btnAddPlane))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(landingMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(datePickerLanding, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(landingHour)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFlightNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlightNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightNumberActionPerformed

    private void takeOffHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeOffHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_takeOffHourActionPerformed

    private void landingHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landingHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landingHourActionPerformed

    private void btnAddPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlaneActionPerformed
        String pId = txtAirPlaneId.getText();
        String pModel = String.valueOf(comboBoxAirplaneModel.getSelectedItem());
        int pAge = Integer.parseInt(txtAirPlaneAge.getText());
        int pSeats = Integer.parseInt(txtAirPlaneSeats.getText());
        Date takeOffTime = (Date) datePickerTakeOff.getValue();
        int toHour = Integer.parseInt(String.valueOf(takeOffHour.getText()));
        int toMin = Integer.parseInt(String.valueOf(takeOffMin.getText()));
        takeOffTime.setHours(toHour);
        takeOffTime.setMinutes(toMin);
        Date landingTime = (Date) datePickerLanding.getValue();
        int lHour = Integer.parseInt(String.valueOf(landingHour.getText()));
        int loMin = Integer.parseInt(String.valueOf(landingMin.getText()));
        landingTime.setHours(lHour);
        landingTime.setMinutes(loMin);
        String flightNumber = txtFlightNumber.getText();
        String takeOffCountry = txtTakeOffCountry.getText();
        String takeOffCity = txtTakeOffCity.getText();
        Address takeOffAdd = new Address(takeOffCountry, takeOffCity);
        String lCountry = txtLandingCountry.getText();
        String landingCity = txtLandingCity.getText();
        Address landingAdd = new Address(lCountry, landingCity);

        Airplane airplane = new Airplane(pId, pModel, pAge, pSeats);
        Flight flight = new Flight(flightNumber, airliner.getName(), airplane, takeOffTime, landingTime, takeOffAdd, landingAdd);
        airplane.setFlight(flight);
        airliner.addFlight(flight);

        airliner.getFlightList().add(flight);
        airliner.getAirplaneList().add(airplane);
        AirlinerDirectory.addAirliner(airliner);
        AirlinerProfile airlinerProfile = new AirlinerProfile(airliner,flight,airplane);
        AirlinerProfileList.addAirlinerProfile(airlinerProfile);
        ManageAirlinersJPanel.show(this.cardSequenceJPanel, this.airliner);
    }//GEN-LAST:event_btnAddPlaneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPlane;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> comboBoxAirplaneModel;
    private com.eltima.components.ui.DatePicker datePickerLanding;
    private com.eltima.components.ui.DatePicker datePickerTakeOff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField landingHour;
    private javax.swing.JTextField landingMin;
    private javax.swing.JLabel lblAirplaneAge;
    private javax.swing.JLabel lblAirplaneId;
    private javax.swing.JLabel lblAirplaneModel;
    private javax.swing.JLabel lblAirplaneSeats;
    private javax.swing.JLabel lblLandingTime;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JTextField takeOffHour;
    private javax.swing.JTextField takeOffMin;
    private javax.swing.JTextField txtAirPlaneAge;
    private javax.swing.JTextField txtAirPlaneId;
    private javax.swing.JTextField txtAirPlaneSeats;
    private javax.swing.JTextField txtAirliner;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtLandingCity;
    private javax.swing.JTextField txtLandingCountry;
    private javax.swing.JTextField txtTakeOffCity;
    private javax.swing.JTextField txtTakeOffCountry;
    // End of variables declaration//GEN-END:variables
}
