/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManagerAirliners;

import Business.Airliners.Airliner;
import Business.Airliners.AirlinerDirectory;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author wangcong
 */
public class CreateAirlinerJPanel extends javax.swing.JPanel {

    private final JPanel cardSequenceJPanel;
    /**
     * Creates new form CreateAirlinerJPanel
     */
    public CreateAirlinerJPanel(JPanel cardSequenceJPanel) {
        this.cardSequenceJPanel = cardSequenceJPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAirplaneId = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        lblAirplaneModel = new javax.swing.JLabel();
        lblAirplaneAge = new javax.swing.JLabel();
        txtAirlinerCity = new javax.swing.JTextField();
        lblAirplaneSeats = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        txtAirlinerCountry = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setText("Create Airliner");

        lblAirplaneId.setText("Airliner Name:");

        lblAirplaneModel.setText("Airliner Country");

        lblAirplaneAge.setText("Airliner City");

        lblAirplaneSeats.setText("Password:");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnBack1.setText("<<Back");

        btnCreate.setText("Create!");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnBack1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAirplaneSeats)
                            .addComponent(lblAirplaneAge)
                            .addComponent(lblAirplaneModel)
                            .addComponent(lblAirplaneId))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAirlinerCity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAirlinerCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblTitle)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnBack1)
                .addGap(1, 1, 1)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirplaneId)
                    .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirplaneModel)
                    .addComponent(txtAirlinerCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirplaneAge)
                    .addComponent(txtAirlinerCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirplaneSeats)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreate)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String airlinerName = txtAirlinerName.getText();
        String airlinerCountry = txtAirlinerCountry.getText();
        String airlinerCity = txtAirlinerCity.getText();
        String password = txtPassword.getText();
        Airliner airliner = new Airliner(airlinerName, airlinerCountry, airlinerCity, password);
        AirlinerDirectory.addAirliner(airliner);

        ManageAirlinersJPanel.show(this.cardSequenceJPanel, airliner);
//        ManageAirlinersJPanel createAirlinerJPanel = new ManageAirlinersJPanel(this.cardSequenceJPanel, airliner);
//        this.cardSequenceJPanel.add("CreateAirlinerJPanel", createAirlinerJPanel);
//        CardLayout layout = (CardLayout) this.cardSequenceJPanel.getLayout();
//        layout.next(this.cardSequenceJPanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblAirplaneAge;
    private javax.swing.JLabel lblAirplaneId;
    private javax.swing.JLabel lblAirplaneModel;
    private javax.swing.JLabel lblAirplaneSeats;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAirlinerCity;
    private javax.swing.JTextField txtAirlinerCountry;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
